# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'
install! 'cocoapods', :disable_input_output_paths => true

target 'YTPlayerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'YTPlayer', :path => '../YTPlayer'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
